# Generated by Django 4.0.5 on 2022-07-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('File_transfer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_reg',
            name='Recieve_user',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='file_reg',
            name='Upload_user',
            field=models.CharField(max_length=256),
        ),
    ]
