# Generated by Django 4.0.5 on 2022-08-17 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('File_transfer', '0003_alter_file_reg_upload_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file_reg',
            name='Encryption_status',
        ),
        migrations.RemoveField(
            model_name='file_reg',
            name='Recieve_user',
        ),
        migrations.RemoveField(
            model_name='file_reg',
            name='Upload_time',
        ),
        migrations.RemoveField(
            model_name='file_reg',
            name='Upload_user',
        ),
        migrations.AlterField(
            model_name='file_reg',
            name='File_id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
